[theme]
base = "light"
primaryColor = "#6FB443"                # Citadel green (accent)
backgroundColor = "#FFFFFF"            # White background
secondaryBackgroundColor = "#F2F2F2"   # Light gray panel/card areas
textColor = "#003366"                  # Deep navy text (Citadel brand)
font = "sans serif"

[multipage]
show_navigation = false
